version: '3'

services:
  web:
    build:
      context: .
      dockerfile: build-src/development/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./build-src/:/data/build-src/:ro
      - ./_build/:/data/_build/:ro
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # for access on host
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db-data: